# Generated by Django 2.0.4 on 2018-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('is_citizen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Are you a Botswana citizen?')),
                ('is_married_citizen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=10, verbose_name='If not a citizen, are you legally married to a Botswana citizen?')),
                ('marriage_proof', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=10, verbose_name='Has the participant produced the marriage certificate, as proof?')),
                ('is_literate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Is the participant literate?')),
                ('literate_witness_avail', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=10, verbose_name='If illeterate, is there a literate witness available?')),
                ('is_minor', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('guardian_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=10, verbose_name='If minor, is there a guardian available?')),
            ],
        ),
    ]
